// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { getPublicEnv } from '@/lib/runtimeEnv';
import type { Database } from './types';

const SUPABASE_URL = getPublicEnv('VITE_SUPABASE_URL');
const SUPABASE_PROJECT_ID = getPublicEnv('VITE_SUPABASE_PROJECT_ID');
const SUPABASE_PUBLISHABLE_KEY = getPublicEnv('VITE_SUPABASE_PUBLISHABLE_KEY');
const FALLBACK_SUPABASE_URL = 'https://missing-project.supabase.co';
const FALLBACK_SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWYiOiJtaXNzaW5nLXByb2plY3QiLCJyb2xlIjoiYW5vbiIsImlhdCI6MCwiZXhwIjoyNTM0MDIzMDA3OTl9.signature-placeholder';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

function safeSupabaseUrl(): string {
  const raw = typeof SUPABASE_URL === 'string' ? SUPABASE_URL.trim() : '';
  if (raw) return raw;
  const pid = typeof SUPABASE_PROJECT_ID === 'string' ? SUPABASE_PROJECT_ID.trim() : '';
  if (pid) return `https://${pid}.supabase.co`;
  return '';
}

function createMemoryStorage(): Storage {
  const map = new Map<string, string>();
  return {
    get length() {
      return map.size;
    },
    clear() {
      map.clear();
    },
    getItem(key: string) {
      return map.has(key) ? map.get(key)! : null;
    },
    key(index: number) {
      return Array.from(map.keys())[index] ?? null;
    },
    removeItem(key: string) {
      map.delete(key);
    },
    setItem(key: string, value: string) {
      map.set(key, String(value));
    },
  } as Storage;
}

function safeAuthStorage(): Storage {
  try {
    const testKey = '__hexology_storage_test__';
    localStorage.setItem(testKey, '1');
    localStorage.removeItem(testKey);
    return localStorage;
  } catch {
    // Some environments (privacy mode, embedded contexts) block storage access.
    return createMemoryStorage();
  }
}

function getSupabaseConfigErrorInternal(): string | null {
  const resolvedUrl = safeSupabaseUrl();

  if (!resolvedUrl) {
    return 'Missing VITE_SUPABASE_URL / SUPABASE_URL';
  }

  if (!SUPABASE_PUBLISHABLE_KEY) {
    return 'Missing VITE_SUPABASE_PUBLISHABLE_KEY / SUPABASE_PUBLISHABLE_KEY';
  }

  if (resolvedUrl.includes('your-project-id')) {
    return 'Frontend is still using the example Supabase URL';
  }

  if (SUPABASE_PUBLISHABLE_KEY.includes('your-anon-key')) {
    return 'Frontend is still using the example publishable key';
  }

  return null;
}

const resolvedSupabaseUrl = safeSupabaseUrl();
const supabaseConfigError = getSupabaseConfigErrorInternal();

export function getSupabaseConfigError(): string | null {
  return supabaseConfigError;
}

export function getSupabaseConfigSnapshot() {
  return {
    configError: supabaseConfigError,
    resolvedUrl: resolvedSupabaseUrl,
    projectId: SUPABASE_PROJECT_ID,
    publishableKeyPresent: Boolean(SUPABASE_PUBLISHABLE_KEY),
  };
}

export const supabase = createClient<Database>(
  resolvedSupabaseUrl || FALLBACK_SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY || FALLBACK_SUPABASE_PUBLISHABLE_KEY,
  {
  auth: {
    storage: safeAuthStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});
